# Generated by Django 5.1.3 on 2025-02-18 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("briefly_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brieflyuser",
            name="country",
            field=models.CharField(
                choices=[
                    ("ae", "United Arab Emirates"),
                    ("ar", "Argentina"),
                    ("at", "Austria"),
                    ("au", "Australia"),
                    ("be", "Belgium"),
                    ("bg", "Bulgaria"),
                    ("br", "Brazil"),
                    ("ca", "Canada"),
                    ("ch", "Switzerland"),
                    ("cn", "China"),
                    ("co", "Colombia"),
                    ("cz", "Czech Republic"),
                    ("de", "Germany"),
                    ("eg", "Egypt"),
                    ("fr", "France"),
                    ("gb", "United Kingdom"),
                    ("gr", "Greece"),
                    ("hk", "Hong Kong"),
                    ("hu", "Hungary"),
                    ("id", "Indonesia"),
                    ("ie", "Ireland"),
                    ("il", "Israel"),
                    ("in", "India"),
                    ("it", "Italy"),
                    ("jp", "Japan"),
                    ("kr", "South Korea"),
                    ("lt", "Lithuania"),
                    ("lv", "Latvia"),
                    ("ma", "Morocco"),
                    ("mx", "Mexico"),
                    ("my", "Malaysia"),
                    ("ng", "Nigeria"),
                    ("nl", "Netherlands"),
                    ("no", "Norway"),
                    ("nz", "New Zealand"),
                    ("ph", "Philippines"),
                    ("pl", "Poland"),
                    ("pt", "Portugal"),
                    ("ro", "Romania"),
                    ("rs", "Serbia"),
                    ("ru", "Russia"),
                    ("sa", "Saudi Arabia"),
                    ("se", "Sweden"),
                    ("sg", "Singapore"),
                    ("si", "Slovenia"),
                    ("sk", "Slovakia"),
                    ("th", "Thailand"),
                    ("tr", "Turkey"),
                    ("tw", "Taiwan"),
                    ("ua", "Ukraine"),
                    ("us", "United States"),
                    ("ve", "Venezuela"),
                    ("za", "South Africa"),
                ],
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="CategoryName",
            field=models.CharField(
                choices=[
                    ("business", "business"),
                    ("entertainment", "entertainment"),
                    ("general", "general"),
                    ("health", "health"),
                    ("science", "science"),
                    ("sports", "sports"),
                    ("technology", "technology"),
                ],
                max_length=20,
                unique=True,
            ),
        ),
    ]
