# Generated by Django 5.1.3 on 2025-03-06 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('briefly_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='Region',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='Url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
