# Generated by Django 5.1.3 on 2025-03-02 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("briefly_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="usercategory",
            unique_together={("User", "Category")},
        ),
    ]
