# Generated by Django 5.1.3 on 2025-03-06 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('briefly_app', '0002_newsarticle_region_newsarticle_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsarticle',
            name='Region',
        ),
        migrations.RemoveField(
            model_name='newsarticle',
            name='Url',
        ),
    ]
