# Generated by Django 5.1.3 on 2025-02-24 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("briefly_app", "0002_alter_brieflyuser_country_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="newsarticle",
            old_name="CategoryID",
            new_name="Category",
        ),
        migrations.RenameField(
            model_name="savednews",
            old_name="NewsID",
            new_name="News",
        ),
        migrations.RenameField(
            model_name="savednews",
            old_name="UserID",
            new_name="User",
        ),
        migrations.RenameField(
            model_name="usercategory",
            old_name="CategoryID",
            new_name="Category",
        ),
        migrations.RenameField(
            model_name="usercategory",
            old_name="UserID",
            new_name="User",
        ),
        migrations.RenameField(
            model_name="viewednews",
            old_name="NewsID",
            new_name="News",
        ),
        migrations.RenameField(
            model_name="viewednews",
            old_name="UserID",
            new_name="User",
        ),
    ]
