# Generated by Django 5.1.3 on 2025-03-07 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('briefly_app', '0003_remove_newsarticle_region_remove_newsarticle_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='Region',
            field=models.TextField(max_length=2, null=True),
        ),
    ]
