# Generated by Django 5.1.3 on 2025-03-07 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('briefly_app', '0004_newsarticle_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='Url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
