# Generated by Django 5.1.3 on 2025-03-07 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('briefly_app', '0002_alter_usercategory_unique_together'),
        ('briefly_app', '0005_newsarticle_url'),
    ]

    operations = [
    ]
