# Generated by Django 5.1.6 on 2025-03-10 16:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("briefly_app", "0006_merge_20250307_1632"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsarticle",
            name="Date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
