# Generated by Django 5.1.3 on 2025-03-10 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('briefly_app', '0007_alter_newsarticle_date'),
        ('briefly_app', '0007_savednews_unique_user_saved_news_and_more'),
    ]

    operations = [
    ]
