# Generated by Django 5.1.3 on 2025-03-13 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('briefly_app', '0008_merge_20250310_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='Content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
